server:
  servlet:
    context-path:
      /demo-spring-redis

spring:
  data:
    redis:
      host:
        localhost
      port:
        6379
      password:
        eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    mongodb:
      host: localhost
      port: 27017
      database: authenticatorDB
      username: mongoadmin
      password: 1234

# Desactivar el logger
logging:
  config:
    classpath:logback.xml
